name: Infrastructure as Code - Red Hawks Game Cow
run-name: "iac - Env: @${{ github.ref_name }} - @${{ github.actor }}"

on:
  push:
    branches:
      - dev
      - prod
    paths:
      - .github/workflows/iac.yaml
      - api/**
      - common/core/**
      - web-sockets/**
      - infrastructure-as-code/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  WORKING_DIR: ./infrastructure-as-code
  FUNCTIONS_DEPENDENCY_DIR: ./common/core
  AWS_REGION: us-east-1
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
  ENVIRONMENT: ${{ github.ref_name }}
  REGION: usea1
  PRODUCT: rhgc
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

jobs:
  aws-cdk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
          cache-dependency-path: ${{ env.WORKING_DIR }}/pnpm-lock.yaml

      - name: Install AWS CDK & esbuild globally
        shell: bash
        run: pnpm add -g aws-cdk esbuild

      - name: Install AWS CDK dependencies
        working-directory: ${{ env.WORKING_DIR }}
        shell: bash
        run: pnpm install --frozen-lockfile --prod

      - name: Install Functions dependencies
        working-directory: ${{ env.FUNCTIONS_DEPENDENCY_DIR }}
        shell: bash
        run: pnpm install --frozen-lockfile --prod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}

      - name: Deploy Infrastructure as Code
        working-directory: ${{ env.WORKING_DIR }}
        shell: bash
        run: cdk deploy --all --require-approval never
